org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=18080 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=18080 -Dhttp.nonProxyHosts=localhost|127.0.0.1
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.internal.http.connectionTimeout=300000
org.gradle.internal.http.socketTimeout=300000
org.gradle.internal.repository.max.retries=10
org.gradle.caching=true
# HTTP 代理（直连外网不通，必须走）
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.java.net.preferIPv4Stack=true
